Adding apps3
AnnMarieW/dash-app-gallery pull request #63
Opened 2022-06-27 02:50 UTC by RodrigoVanzelotti

Just did my last modifications to the app, until creating-and-updating-figures.
I dont have any exp with the bad apple example, so I will leave it as its, please someone fix it.

2022-06-27 04:50 UTC, Coding-with-Adam commented on pages/3d-scatter-plots.py
> +- [Regular Callbacks](https://dash.plotly.com/basic-callbacks)
```suggestion
```

2022-06-27 04:53 UTC, Coding-with-Adam commented on pages/3d-scatter-plots.py
> +- [RangeSlider](https://plotly.com/python/range-slider/)
This rangeslider is a dash core component. Can you please update the link to the rangeslider component in the dash docs. https://dash.plotly.com/dash-core-components/rangeslider

2022-06-27 04:54 UTC, Coding-with-Adam commented on pages/animations.py
> +- [Regular Callbacks](https://dash.plotly.com/basic-callbacks)
To be removed.

2022-06-27 04:58 UTC, Coding-with-Adam commented on pages/axes.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
I can't see a dropdown in the code. But I saw a button. Can you please replace this link with the link to the html.button. https://dash.plotly.com/dash-html-components/button

2022-06-27 04:59 UTC, Coding-with-Adam commented on pages/axes.py
> +- [Bar Plot](https://plotly.com/python/bar-charts/)
although it looks like a bar plot, the code is actually using a px.histogram. Can you please replace this.

2022-06-27 05:00 UTC, Coding-with-Adam commented on pages/axes.py
>  Learn how to adjust axes properties in Python - axes titles, styling and coloring axes and grid lines, ticks, tick labels and more.
I think this sentence needs to be removed because it doesn't belong here.

2022-06-27 05:04 UTC, Coding-with-Adam commented on pages/bar-charts.py
> +- [Regular Callbacks](https://dash.plotly.com/basic-callbacks)
To be removed.

2022-06-27 05:08 UTC, Coding-with-Adam commented on pages/bar-charts.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
Let's call it just Dropdown. Please remove the dcc part.

2022-06-27 05:09 UTC, Coding-with-Adam commented on pages/box-plots.py
> +- [Dcc.Checklist](https://dash.plotly.com/dash-core-components/checklist)
Let's call it just RadioItems and Checklist. Please remove the dcc part.

2022-06-27 05:11 UTC, Coding-with-Adam commented on pages/box-plots.py
>  The ends of the box represent the lower and upper quartiles, while the median (second quartile) is marked by a line inside the box.
@RodrigoVanzelotti let's remove this explanation. I want to make sure it's consistent with other files in the Pages folder. None of the other files have an explanation inside the notes sections.

2022-06-27 05:14 UTC, Coding-with-Adam commented on pages/builtin-colorscales.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
remove dcc. Just keep Dropdown

2022-06-27 05:14 UTC, Coding-with-Adam commented on pages/builtin-colorscales.py
>  How to set, create and control continuous color scales and color bars in scatter, bar, map and heatmap figures.
```suggestion
```

2022-06-27 05:16 UTC, Coding-with-Adam commented on pages/builtin-colorscales.py
> +
This app uses the scatter plot also.
@RodrigoVanzelotti can you please add a link to the plotly docs scatter Plot, under the Continuous Color Scales link.

2022-06-27 05:19 UTC, Coding-with-Adam requested changes
Nice PR. Thanks @RodrigoVanzelotti . I added a few changes that need to be made. 
I've reviewed up to the builtin colorscales file. Tomorrow, I'll continue the review from the candlestick-charts to the end. 
But much of what I requested in this first review can be implemented in the remaining files I haven't looked at yet. For examples, remove regular-callback links if you added them, and call the components by their name instead of dcc.Dropdown or dcc.RadioItems, etc.

2022-06-29 16:57 UTC, Coding-with-Adam commented on pages/candlestick-charts.py
```suggestion
```

2022-06-29 16:59 UTC, Coding-with-Adam commented on pages/candlestick-charts.py
>  How to make interactive candlestick charts in Python with Plotly. Six examples of candlestick charts with Pandas, time series, and yahoo finance data.
```suggestion
```

2022-06-29 17:09 UTC, Coding-with-Adam commented on pages/choropleth-maps.py
> +    __name__, description="Interactive Mapbox Choropleth Map of US Counties. This app has a top-bottom layout and a regular-callback."
```suggestion
    __name__, description="Interactive Mapbox Choropleth Map of Montreal. This app has a top-bottom layout and a regular-callback."
```

2022-06-29 17:11 UTC, Coding-with-Adam commented on pages/choropleth-maps.py
> +- [Dcc.RadioItems](https://dash.plotly.com/dash-core-components/radioitems)
```suggestion
- [RadioItems](https://dash.plotly.com/dash-core-components/radioitems)
```

2022-06-29 17:12 UTC, Coding-with-Adam commented on pages/choropleth-maps.py
>  How to make an interactive Mapbox Choropleth Map of US Counties.
```suggestion
- [Choropleth maps](https://plotly.com/python/choropleth-maps/)

```

2022-06-29 17:18 UTC, Coding-with-Adam commented on pages/creating-and-updating-figures.py
> +- [Dcc.Slider](https://dash.plotly.com/dash-core-components/slider)
```suggestion
dash.register_page(__name__, description="Updating the figure's title's font size and text, using a Slider and an Input. This app has a top-bottom layout and a regular-callback.")

filename = __name__.split("pages.")[1]


notes = """
#### Dash Components in App:  
- [Input](https://dash.plotly.com/dash-core-components/input)
- [Slider](https://dash.plotly.com/dash-core-components/slider)
```

2022-06-29 17:20 UTC, Coding-with-Adam commented on pages/creating-and-updating-figures.py
```suggestion
- [Creating and updating figures](https://plotly.com/python/creating-and-updating-figures)
```

2022-06-29 17:25 UTC, Coding-with-Adam commented on pages/getting-started.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```suggestion
- [Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```

2022-06-29 17:28 UTC, Coding-with-Adam commented on pages/getting-started.py
```suggestion
- [Getting started with Plotly](https://plotly.com/python/getting-started/)

```

2022-06-29 17:31 UTC, Coding-with-Adam requested changes
Hi @RodrigoVanzelotti 
I just finished updating all the files from candlestick-charts to the end. So, all that is left is to implement the updates from 3d-scatter-plots to builtin-colorscale.
Thank you

2022-06-29 17:58 UTC, IcToxi commented
@Coding-with-Adam 
Hi Adam, I noticed that you are revising the description and contributors' info. And I have a suggestion. Would you consider adding the last modified guy's information? I'd love to see the code I submit with some necessary changes to make it more readable and stable, and I've checked Allow Changes when submitting the PR. But I don't think all the changes are necessary, some of the code has changed beyond recognition by this point. Embarrassingly, contributors need to be the title for those stupid changes made before the intent of the original code was fully understood.

2022-06-30 06:53 UTC, IcToxi commented
@Coding-with-Adam  Sorry, I meant modifiers. Because some newly added statements are confusing,  combined with the original code, and that's not what the contributors did.

2022-07-06 15:16 UTC, Coding-with-Adam commented on pages/animations.py
> +- [Regular Callbacks](https://dash.plotly.com/basic-callbacks)
```suggestion
```

2022-07-06 15:19 UTC, Coding-with-Adam commented on pages/axes.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```suggestion
- [Button](https://dash.plotly.com/dash-html-components/button)
```

2022-07-06 15:21 UTC, Coding-with-Adam commented on pages/axes.py
> +- [Bar Plot](https://plotly.com/python/bar-charts/)
```suggestion
- [Histogram](https://plotly.com/python/histograms)
```

2022-07-06 15:22 UTC, Coding-with-Adam commented on pages/axes.py
```suggestion
```

2022-07-06 15:54 UTC, Coding-with-Adam commented on pages/bar-charts.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```suggestion
- [Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```

2022-07-06 15:54 UTC, Coding-with-Adam commented on pages/bar-charts.py
> +- [Regular Callbacks](https://dash.plotly.com/basic-callbacks)
```suggestion
```

2022-07-06 15:55 UTC, Coding-with-Adam commented on pages/builtin-colorscales.py
> +- [Dcc.Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```suggestion
- [Dropdown](https://dash.plotly.com/dash-core-components/dropdown)
```

2022-07-06 15:56 UTC, Coding-with-Adam commented on pages/box-plots.py
> +- [Dcc.Checklist](https://dash.plotly.com/dash-core-components/checklist)
```suggestion
- [RadioItems](https://dash.plotly.com/dash-core-components/radioitems)
- [Checklist](https://dash.plotly.com/dash-core-components/checklist)
```

2022-07-06 15:56 UTC, Coding-with-Adam commented on pages/box-plots.py
>  The ends of the box represent the lower and upper quartiles, while the median (second quartile) is marked by a line inside the box.
```suggestion
```

2022-07-06 15:57 UTC, Coding-with-Adam commented on pages/box-plots.py
```suggestion
```

2022-07-06 15:58 UTC, Coding-with-Adam commented on pages/builtin-colorscales.py
> +
```suggestion
- [Scatter Plot](https://plotly.com/python/line-and-scatter/)
```

2022-07-06 15:59 UTC, Coding-with-Adam approved these changes
All good.

2022-07-06 16:00 UTC, merged